### ISSUE TITLE
Suggestion: Project should not generate HTTP clients unless necessary

### ISSUE THREAD

**Issue by monokrome** [ctison/graphql-codegen-golang#26]
This project is awesome! With that said, I'd like to start a conversation to help improve it. It seems to me like the output from this library may be unnecessarily prescriptive of specific use-cases, and I'm wondering if you're open to reconsidering some decisions.

The core thing here is that it seems outside of the scope of this project & behaves differently than other plugins by generating it's own client code - although that may be a nice optional feature to enable. Consider the following configuration and schema:

```graphql
type Error {
  message: String!
}
```

```yaml
schema: './errors.gql'
generates:
  './dist/errors.go':
    plugins:
      - 'golang'
  './dist/errors.ts':
    plugins:
      - 'typescript'
```

If we look at the output typescript, we get a bunch of types without any additional code prescriptive of HTTP, clients, etc:

```typescript
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
};

export type Error = {
  __typename?: 'Error';
  message: Scalars['String'];
};
```

Similarly, I'd expect that the output for Go would be something like:

```
package graphql

type Int int32
type Float float64
type Boolean bool
type String string
type ID string

type Error struct {
  Message String `json:"message"`
}
```

A reason - among others - that the client should not be added (or should at least be optional) is because people use GraphQL in ways that may not be consistent with what the Client generated by this library exposes. Some use cases that don't fit the output here include, but are not limited to:

- Some developers use GraphQL over websockets
- Some developers are using their own client libraries (consider organizations where there is more complex infrastructure in place)

EDIT: It's possible that more complicated use-cases should include a client (and probably do with typescript) but I think that stuff should not be added for projects which are only using **graphql-code-generator** for types and not queries.

**Comment by ctison** [comment]
Hello,

Thanks for your feedback.

I just released [v0.2.0-beta.0][^1] where I introduced `generateHTTPClient` (`true` by default) that you can set to `false` to disable the generation of the HTTP client.

Please let me know if it solves your issues.

[^1]: https://github.com/ctison/graphql-codegen-golang/releases/tag/v0.2.0-beta.0
